### ISSUE TITLE
windows pip install -v . error

### ISSUE THREAD

**Issue by hjmhjms** [pthom/srcml_caller#3]
-- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - success
  --------------------------------------------------------------------------------

  Configuring Project
    Working directory:
      \tmp\srcml_caller\_skbuild\win-amd64-3.11\cmake-build
    Command:
      'C:\Users\jameshuo\AppData\Local\Temp\pip-build-env-dp8m5wgf\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' '\tmp\srcml_caller' -G Ninja -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=\tmp\srcml_caller\_skbuild\win-amd64-3.11\cmake-install\bindings\srcml_caller' -DPYTHON_VERSION_STRING:STRING=3.11.3 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\jameshuo\AppData\Local\Temp\pip-build-env-dp8m5wgf\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Python311\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Python311\Include' '-DPYTHON_LIBRARY:PATH=C:\Python311\libs\python311.lib' '-DPython_EXECUTABLE:PATH=C:\Python311\python.exe' '-DPython_ROOT_DIR:PATH=C:\Python311' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Python311\Include' '-DPython_LIBRARY:PATH=C:\Python311\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=C:\Python311\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Python311' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Python311\Include' '-DPython3_LIBRARY:PATH=C:\Python311\libs\python311.lib' -DCMAKE_BUILD_TYPE:STRING=Release

  Not searching for unused variables given on the command line.
  'C:/Python311/python.exe' '-c' 'import pybind11; print(pybind11.get_cmake_dir())'
  -- Found pybind11: C:/Users/jameshuo/AppData/Local/Temp/pip-build-env-dp8m5wgf/overlay/Lib/site-packages/pybind11/include (found version "2.11.0")
  -- Project version: 1.0.0
  CMake Error at C:/Users/jameshuo/AppData/Local/Temp/pip-build-env-dp8m5wgf/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find LibArchive (missing: LibArchive_LIBRARY
    LibArchive_INCLUDE_DIR) (Required is at least version "3")
  Call Stack (most recent call first):
    C:/Users/jameshuo/AppData/Local/Temp/pip-build-env-dp8m5wgf/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
    C:/Users/jameshuo/AppData/Local/Temp/pip-build-env-dp8m5wgf/overlay/Lib/site-packages/cmake/data/share/cmake-3.26/Modules/FindLibArchive.cmake:67 (find_package_handle_standard_args)
    external/srcML/src/client/CMakeLists.txt:9 (find_package)

  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "C:\Users\jameshuo\AppData\Local\Temp\pip-build-env-dp8m5wgf\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
      env = cmkr.configure(
            ^^^^^^^^^^^^^^^
    File "C:\Users\jameshuo\AppData\Local\Temp\pip-build-env-dp8m5wgf\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
      raise SKBuildError(msg)

  An error occurred while configuring with CMake.
    Command:
      'C:\Users\jameshuo\AppData\Local\Temp\pip-build-env-dp8m5wgf\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' '\tmp\srcml_caller' -G Ninja -D_SKBUILD_FORCE_MSVC=1930 --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=\tmp\srcml_caller\_skbuild\win-amd64-3.11\cmake-install\bindings\srcml_caller' -DPYTHON_VERSION_STRING:STRING=3.11.3 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\jameshuo\AppData\Local\Temp\pip-build-env-dp8m5wgf\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Python311\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Python311\Include' '-DPYTHON_LIBRARY:PATH=C:\Python311\libs\python311.lib' '-DPython_EXECUTABLE:PATH=C:\Python311\python.exe' '-DPython_ROOT_DIR:PATH=C:\Python311' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Python311\Include' '-DPython_LIBRARY:PATH=C:\Python311\libs\python311.lib' '-DPython3_EXECUTABLE:PATH=C:\Python311\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Python311' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Python311\Include' '-DPython3_LIBRARY:PATH=C:\Python311\libs\python311.lib' -DCMAKE_BUILD_TYPE:STRING=Release
    Source directory:
     \tmp\srcml_caller
    Working directory:
      \srcml_caller\_skbuild\win-amd64-3.11\cmake-build
  Please see CMake's output for more information.

  error: subprocess-exited-with-error

  × Building wheel for srcml-caller (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: 'C:\Python311\python.exe' 'C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py' build_wheel 'C:\Users\jameshuo\AppData\Local\Temp\tmpi0wfu1br'
  cwd: \tmp\srcml_caller
  Building wheel for srcml-caller (pyproject.toml) ... error
  ERROR: Failed building wheel for srcml-caller
Failed to build srcml-caller
ERROR: Could not build wheels for srcml-caller, which is required to install pyproject.toml-based projects

**Comment by pthom** [comment]
Hello,

As mentioned in the Readme, this project does not currently build on Windows. Porting it to windows would require to patch the srcML source, and it is not that easy.
As this project is mainly dedicated to generating and transforming code (and not intended for final users) you try to build it on a linux machine?

**Comment by pthom** [comment]
It should now work on windows
